name: makdumanarchitect
description: You can create a clean structure and benefit from its features
version: 1.0.0
homepage: https://github.com/mehmetakdumn604/akdumanarchitect


environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # state management
  provider: ^6.1.2

  # network request
  dio: ^5.8.0

  # local storage
  hive_flutter: ^1.1.0

  # internet connection
  connectivity_plus: ^6.1.3

  # create model easily
  json_annotation: ^4.9.0

  # local notifications
  awesome_notifications: ^0.10.1

  # firebase notifications
  firebase_messaging: ^15.2.3

  # language support
  flutter_localizations:
    sdk: flutter
  easy_localization: ^3.0.7+1

  # in app review package 
  in_app_review: ^2.0.10

  # loading spinner package
  flutter_easyloading: ^3.0.5

  # responsive package
  flutter_screenutil: ^5.9.3

  # svg image package
  flutter_svg: ^2.0.9

  # firebase packages
  firebase_remote_config: ^5.4.1
  firebase_crashlytics: ^4.3.3
  firebase_analytics: ^11.4.3

  # tracking
  app_tracking_transparency: ^2.0.6+1

  # purchases
  purchases_flutter: ^8.5.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  flutter_lints: ^3.0.1
  json_serializable: ^6.7.1
  # Asset generation
  flutter_gen: ^5.4.0
  flutter_gen_runner: ^5.4.0
  # native splash screen
  flutter_native_splash: ^2.3.9
  # app icon
  flutter_launcher_icons: ^0.13.1
  # cache model generator
  hive_generator: ^2.0.1
  # package name change
  package_rename: ^1.6.0



flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/translations/

flutter_gen:
  output: lib/src/core/assets_gen/
  line_length: 80

  integrations:
    flutter_svg: true
    lottie: true
    # flare_flutter: true
    # rive: true


flutter_native_splash:
  color: "#D93B6A"
  image: "assets/images/app_logo.png"
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center
  fullscreen: true

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/app_logo.png"
  min_sdk_android: 21
  remove_alpha_ios: true

package_rename_config:
  android:
    app_name: New App Name
    package_name: com.new.app
    override_old_package: com.old.app
  ios:
    app_name: # (String) The display name of the ios app
    bundle_name: # (String) The bundle name of the ios app
    package_name: # (String) The product bundle identifier of the ios app
